--application.properties(spring.sql.init.mode)で実行指定
--参考：エンティティクラスから自動生成されたDDL
create table local_user (
    id integer generated by default as identity,
    email varchar(255),
    name varchar(255),
    primary key (id)
)
